FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl gcc libffi-dev
RUN curl -Ls https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app
COPY . .

ENV PYTHONPATH="/app"
RUN uv pip sync --system ./service/service_b/pyproject.toml
CMD ["python3", "./service/service_b/main.py"]