services:
  auth-service:
    container_name: auth-service
    build:
      dockerfile: Dockerfile.auth-service
      context: ../
    volumes:
      - ../docs/api:/app/docs/api
      - ../service/auth_service:/app/service/auth_service
    networks:
      - app-network
    restart: always

  service_a:
    container_name: service_a
    build:
      dockerfile: Dockerfile.service_a
      context: ../
    volumes:
      - ../docs/api:/app/docs/api
      - ../service/service_a:/app/service/service_a
    expose:
      - "9090"
    networks:
      - app-network
    restart: always

  service_b:
    container_name: service_b
    build:
      dockerfile: Dockerfile.service_b
      context: ../
    volumes:
      - ../docs/api:/app/docs/api
      - ../service/service_b:/app/service/service_b
    expose:
      - "9091"
    networks:
      - app-network
    restart: always

  service_c:
    container_name: service_c
    build:
      dockerfile: Dockerfile.service_c
      context: ../
    volumes:
      - ../docs/api:/app/docs/api
      - ../service/service_c:/app/service/service_c
    expose:
      - "9092"
    networks:
      - app-network
    restart: always

#  api-gateway:
#    image: wso2/wso2am:latest
#    container_name: api-gateway
#    ports:
#      - "9080:9090"
#      - "9443:9443"
#    networks:
#      - app-network
#    restart: always

networks:
  app-network:
    driver: bridge