components:
  schemas:
    ErrorResponse:
      properties:
        detail:
          title: Detail
          type: string
      required:
      - detail
      title: ErrorResponse
      type: object
    RefreshTokenRequest:
      properties:
        refresh_token:
          description: Current refresh token
          title: Refresh Token
          type: string
      required:
      - refresh_token
      title: RefreshTokenRequest
      type: object
    UserAuthResponse:
      properties:
        access_token:
          title: Access Token
          type: string
        refresh_token:
          title: Refresh Token
          type: string
      required:
      - access_token
      - refresh_token
      title: UserAuthResponse
      type: object
    UserLoginRequest:
      properties:
        email:
          format: email
          title: Email
          type: string
        password:
          description: Password length must be from 8 to 30 characters long
          maxLength: 30
          minLength: 8
          title: Password
          type: string
      required:
      - email
      - password
      title: UserLoginRequest
      type: object
    UserRegisterRequest:
      properties:
        email:
          format: email
          title: Email
          type: string
        password:
          description: Password length must be from 8 to 30 characters long
          maxLength: 30
          minLength: 8
          title: Password
          type: string
      required:
      - email
      - password
      title: UserRegisterRequest
      type: object
info:
  description: Auth Service
  title: Auth Service
  version: 1.0.0
openapi: 3.1.0
paths:
  /auth/token/refresh:
    post:
      description: Refresh access token for user
      operationId: refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuthResponse'
          description: Successful Response
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Invalid token provided
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error
      summary: Refresh Token
      tags:
      - User Auth
  /auth/tokens:
    post:
      description: Login user
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuthResponse'
          description: Successful Response
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Invalid email or password
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error
      summary: Login
      tags:
      - User Auth
  /users:
    post:
      description: Register user
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuthResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error
      summary: Register
      tags:
      - User Auth
