info:
  description: Service A
  title: Service A
  version: 1.0.0
openapi: 3.1.0
paths:
  /a_health:
    get:
      operationId: service_a_healthCheck
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Health Check
      tags:
      - Service A
