info:
  description: Service C
  title: Service C
  version: 1.0.0
openapi: 3.1.0
paths:
  /c_health:
    get:
      operationId: service_c_healthCheck
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Health Check
      tags:
      - Service C
