info:
  description: Service B
  title: Service B
  version: 1.0.0
openapi: 3.1.0
paths:
  /b_health:
    get:
      operationId: service_b_healthCheck
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Health Check
      tags:
      - Service B
